version: '4.0'

actions:
  generate_dataset:
    run: >
        ehrql:v1 generate-dataset
        analysis/dataset_definition.py
        --test-data-file analysis/test_dataset_definition.py
        --output output/dataset.arrow
    outputs:
      highly_sensitive:
        population: output/dataset.arrow

  generate_measures:
    run: >
        ehrql:v1 generate-measures
        analysis/demo_measures_definition.py
        --output output/demo_measures.csv
    outputs:
      moderately_sensitive:
        dataset: output/demo_measures.csv
