version: '4.0'

actions:
  generate_dataset:
    run: >
        ehrql:v1 generate-dataset
        analysis/dataset_definition.py
        --test-data-file analysis/test_dataset_definition.py
        --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        #population: outputs/dataset.arrow
        dataset: output/dataset.csv.gz
