version: '4.0'

actions:
  generate_dataset:
    run: >
        ehrql:v1 generate-dataset
        analysis/dataset_definition.py
        --test-data-file analysis/test_dataset_definition.py
        --output output/dataset.arrow
    outputs:
      highly_sensitive:
        population: output/dataset.arrow

  generate_measures_conditions:
    run: >
        ehrql:v1 generate-measures
        analysis/demo_measures_definition_conditions.py
        --output output/demo_measures_conditions.csv
    outputs:
      moderately_sensitive:
        dataset: output/demo_measures_conditions.csv

  generate_measures_ages:
    run: >
        ehrql:v1 generate-measures
        analysis/demo_measures_definition_ages.py
        --output output/demo_measures_ages.csv
    outputs:
      moderately_sensitive:
        dataset: output/demo_measures_ages.csv
